# Generated by Django 2.1.3 on 2018-11-22 03:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_manage_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('img', models.TextField()),
                ('ordera', models.IntegerField()),
            ],
            options={
                'db_table': 'product_album',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='date_sell',
            field=models.DateField(default=datetime.datetime(2018, 11, 22, 3, 36, 44, 731614, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 22, 3, 36, 44, 731652, tzinfo=utc)),
        ),
    ]
