# Generated by Django 2.1.3 on 2018-11-28 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_manage_product', '0003_auto_20181128_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_album',
            name='img',
        ),
        migrations.AddField(
            model_name='product_album',
            name='img_url',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product_album',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product_album',
            name='thumbnail_url',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_sell',
            field=models.DateField(default=datetime.datetime(2018, 11, 28, 8, 29, 11, 741134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 28, 8, 29, 11, 741172, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product_album',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 28, 8, 29, 11, 742465, tzinfo=utc)),
        ),
    ]
