# Generated by Django 2.1.3 on 2018-12-10 05:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_manage_product', '0007_auto_20181130_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_sell',
            field=models.DateField(default=datetime.datetime(2018, 12, 10, 5, 15, 58, 268663, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 5, 15, 58, 268740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product_album',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 5, 15, 58, 271871, tzinfo=utc)),
        ),
    ]
