# Generated by Django 2.1.3 on 2018-12-10 05:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_manage_product', '0008_auto_20181210_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_sell',
            field=models.DateField(default=datetime.datetime(2018, 12, 10, 5, 20, 17, 667457, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 5, 20, 17, 667492, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product_album',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 5, 20, 17, 669104, tzinfo=utc)),
        ),
    ]
