# Generated by Django 2.1.3 on 2018-12-10 05:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('top_type', models.IntegerField(null=True)),
                ('uid', models.CharField(max_length=80)),
                ('date_add', models.DateTimeField(default=datetime.datetime(2018, 12, 10, 5, 20, 17, 670620, tzinfo=utc))),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'product_type',
            },
        ),
    ]
