# Generated by Django 2.1.3 on 2018-12-10 08:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_manage_product_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type',
            name='ordera',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 8, 20, 37, 683354, tzinfo=utc)),
        ),
    ]
