# Generated by Django 2.1.3 on 2018-11-08 08:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System_operation_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
                ('type', models.CharField(max_length=6)),
                ('date_add', models.DateTimeField(default=datetime.datetime(2018, 11, 8, 8, 10, 7, 872375, tzinfo=utc))),
            ],
            options={
                'db_table': 'system_operation_record',
            },
        ),
    ]
