# Generated by Django 2.1.3 on 2018-11-30 03:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_system', '0006_auto_20181130_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_operation_record',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 3, 40, 26, 264252, tzinfo=utc)),
        ),
    ]
