# Generated by Django 2.1.3 on 2018-11-08 08:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=225)),
                ('uid', models.CharField(max_length=225)),
                ('premission', models.TextField()),
                ('date_add', models.DateTimeField(default=datetime.datetime(2018, 11, 8, 8, 10, 7, 867165, tzinfo=utc))),
                ('date_login', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'admin_user',
            },
        ),
    ]
